### ISSUE TITLE
Theme is broken

### ISSUE THREAD

**Issue by MechEng70** [dangreco/threedy#10]
downloaded most recent file: 2021.0.a1.2

Theme is still broken when using this resource.  

Configuration:

```
####################################################
#                    OCTOPRINT                     #
#################################################### 
octoprint:
  - host: 172.16.5.240
    api_key: !secret octoprint_api_key
    name: Creality CR-6 SE
    number_of_tools: 1
    sensors:
      monitored_conditions:
        - 'Current State'
        - 'Job Percentage'
        - 'Temperatures'
        - 'Time Elapsed'
        - 'Time Remaining'
```

Card:
```
      - type: 'custom:threedy-card'
        base_entity: sensor.creality_cr_6_se
        name: Creality CR-6e
        printer_type: I3
        monitored:
          - Status
          - ETA
          - Elapsed
          - Hotend
          - Bed
        theme: Default
        font: Roboto
        scale: 0.5
        round: false
```

When Bed or Hotend is removed, the card appears.
