### ISSUE TITLE
power_entity greyed out

### ISSUE THREAD

**Issue by konzolec** [dangreco/threedy#16]
Cannot get power_entity to work, the icon is greyed out (as of not clickable).

Current configuration:

```
type: 'custom:threedy-card'
base_entity: sensor.ender_3
name: Ender 3
printer_type: I3
monitored:
- Status
- ETA
- Elapsed
- Hotend
- Bed
power_entity: switch.sonoff_basic_3d
theme: Default
font: Roboto
scale: 1
round: false
```

Entity ID in HomeAssistant`switch.sonoff_basic_3d`

`switch.sonoff_basic_3d `- Is a sonoff basic powercord

Any idea?

**Comment by mikepowell** [comment]
I'm seeing the same with the `light_entity` attribute as well.
```yaml
  - type: 'custom:threedy-card'
    base_entity: sensor.ender_3_v2
    name: Ender 3 V2
    printer_type: I3
    monitored:
      - Status
      - ETA
      - Elapsed
      - Hotend
      - Bed
    theme: Default
    font: Roboto
    scale: 1
    round: true
    light_entity: light.basement_desk_lamp
```
I've confirmed the entity ID is correct, and works in other parts of home assistant UI.
