### ISSUE TITLE
Feature Request: Keep card opened

### ISSUE THREAD

**Issue by houtknots** [dangreco/threedy#33]
I would like the option to keep te card opened when the printer is connected to home-assistant.

It would also be awesome if the card could always stay opened for dashboard applications.

**Comment by Stephan1908** [comment]
Yes that would be great!
Greetings Stephan

**Comment by CumpsD** [comment]
Can we tweak this with css in the current version?

**Comment by CumpsD** [comment]
Right, fixed:

```css
type: 'custom:mod-card'
style: |
  threedy-card div div div:nth-child(2) {
    height: auto !important;
    opacity: 1 !important;
	transform: none !important;
  }
card:
  type: 'custom:threedy-card'
    .
    .
    .
    <card config>
```
